#!/usr/bin/env sh
set -eu

OWNER="zeerd2"
REPO="almysama-observatory-agent"
SERVER=""
TOKEN=""
NAME=""
VERSION="latest"
INSECURE="false"
INSTALL_DIR="/usr/local/bin"
CONFIG_DIR="/etc/almysama-agent"
CONFIG_FILE="${CONFIG_DIR}/config.json"
SERVICE_FILE="/etc/systemd/system/almysama-agent.service"

say() {
  printf '%s\n' "$*"
}

step() {
  printf '==> %s\n' "$*"
}

ok() {
  printf 'OK  %s\n' "$*"
}

warn() {
  printf 'WARN %s\n' "$*" >&2
}

die() {
  printf 'ERR %s\n' "$*" >&2
  exit 1
}

usage() {
  cat <<'EOF'
Usage:
  install.sh --server https://agent.almysama.tech --token <install-token> [--name node-name]

Options:
  --server     Agent API base URL.
  --token      One-time install token generated by Almysama Observatory.
  --name       Optional display name.
  --owner      GitHub owner, default zeerd2.
  --repo       GitHub repository, default almysama-observatory-agent.
  --version    Release version, default latest.
  --insecure   Skip TLS verification for testing.
EOF
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --server|-s) SERVER="${2:-}"; shift 2 ;;
    --token|-t) TOKEN="${2:-}"; shift 2 ;;
    --name|-n) NAME="${2:-}"; shift 2 ;;
    --owner) OWNER="${2:-}"; shift 2 ;;
    --repo) REPO="${2:-}"; shift 2 ;;
    --version) VERSION="${2:-}"; shift 2 ;;
    --insecure) INSECURE="true"; shift ;;
    --help|-h) usage; exit 0 ;;
    *) echo "Unknown option: $1" >&2; usage; exit 1 ;;
  esac
done

if [ "$(id -u)" -ne 0 ]; then
  die "Please run as root or through sudo."
fi

if [ -z "$SERVER" ] || [ -z "$TOKEN" ]; then
  usage >&2
  exit 1
fi

OS="$(uname -s | tr '[:upper:]' '[:lower:]')"
ARCH_RAW="$(uname -m)"
case "$ARCH_RAW" in
  x86_64|amd64) ARCH="amd64" ;;
  aarch64|arm64) ARCH="arm64" ;;
  armv7l|armv7*) ARCH="armv7" ;;
  *) die "Unsupported architecture: $ARCH_RAW" ;;
esac

if [ "$OS" != "linux" ]; then
  die "Unsupported OS: $OS"
fi

TMP_DIR="$(mktemp -d)"
cleanup() {
  rm -rf "$TMP_DIR"
}
trap cleanup EXIT INT TERM

ASSET="almysama-agent_${OS}_${ARCH}.tar.gz"
if [ "$VERSION" = "latest" ]; then
  URL="https://github.com/${OWNER}/${REPO}/releases/latest/download/${ASSET}"
else
  URL="https://github.com/${OWNER}/${REPO}/releases/download/${VERSION}/${ASSET}"
fi

say "Almysama Observatory Agent installer"
say
step "Checking host"
ok "OS ${OS}, arch ${ARCH}"
ok "Server ${SERVER}"
[ -n "$NAME" ] && ok "Node name ${NAME}"

step "Downloading agent (${VERSION}, ${OS}/${ARCH})"
if command -v curl >/dev/null 2>&1; then
  CURL_TLS=""
  [ "$INSECURE" = "true" ] && CURL_TLS="-k"
  if ! curl -fsSL $CURL_TLS "$URL" -o "$TMP_DIR/agent.tar.gz"; then
    die "Download failed: ${URL}"
  fi
elif command -v wget >/dev/null 2>&1; then
  WGET_TLS=""
  [ "$INSECURE" = "true" ] && WGET_TLS="--no-check-certificate"
  if ! wget -q $WGET_TLS "$URL" -O "$TMP_DIR/agent.tar.gz"; then
    die "Download failed: ${URL}"
  fi
else
  die "curl or wget is required."
fi
ok "Release asset downloaded"

step "Installing files"
tar -xzf "$TMP_DIR/agent.tar.gz" -C "$TMP_DIR"
install -m 0755 "$TMP_DIR/almysama-agent" "${INSTALL_DIR}/almysama-agent"
ok "Binary installed to ${INSTALL_DIR}/almysama-agent"

mkdir -p "$CONFIG_DIR"
chmod 700 "$CONFIG_DIR"
cat > "$CONFIG_FILE" <<EOF
{
  "server": "${SERVER}",
  "install_token": "${TOKEN}",
  "name": "${NAME}",
  "report_interval_seconds": 120,
  "heartbeat_interval_seconds": 30,
  "insecure_tls": ${INSECURE}
}
EOF
chmod 600 "$CONFIG_FILE"
ok "Config written to ${CONFIG_FILE}"

if command -v systemctl >/dev/null 2>&1 && [ -d /run/systemd/system ]; then
  step "Starting systemd service"
  cat > "$SERVICE_FILE" <<'EOF'
[Unit]
Description=Almysama Observatory Agent
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=/usr/local/bin/almysama-agent -config /etc/almysama-agent/config.json
Restart=always
RestartSec=5

NoNewPrivileges=true
ProtectSystem=full
ReadWritePaths=/etc/almysama-agent
PrivateTmp=true

[Install]
WantedBy=multi-user.target
EOF
  systemctl daemon-reload
  systemctl enable almysama-agent >/dev/null
  systemctl restart almysama-agent

  i=0
  AGENT_ID=""
  SERVICE_STATE="unknown"
  while [ "$i" -lt 12 ]; do
    SERVICE_STATE="$(systemctl is-active almysama-agent 2>/dev/null || true)"
    AGENT_ID="$(sed -n 's/.*"agent_id"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' "$CONFIG_FILE" 2>/dev/null | head -n 1)"
    if [ "$SERVICE_STATE" = "active" ] && [ -n "$AGENT_ID" ]; then
      break
    fi
    i=$((i + 1))
    sleep 1
  done

  if [ "$SERVICE_STATE" = "active" ]; then
    ok "Service is active"
  else
    warn "Service state is ${SERVICE_STATE}; check logs with: journalctl -u almysama-agent -n 80 --no-pager"
  fi
elif command -v rc-update >/dev/null 2>&1; then
  step "Starting OpenRC service"
  cat > /etc/init.d/almysama-agent <<'EOF'
#!/sbin/openrc-run
name="Almysama Observatory Agent"
command="/usr/local/bin/almysama-agent"
command_args="-config /etc/almysama-agent/config.json"
command_background=true
pidfile="/run/almysama-agent.pid"
supervisor="supervise-daemon"
respawn_delay=5
depend() {
  need net
}
EOF
  chmod +x /etc/init.d/almysama-agent
  rc-update add almysama-agent default >/dev/null
  rc-service almysama-agent restart
  AGENT_ID="$(sed -n 's/.*"agent_id"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' "$CONFIG_FILE" 2>/dev/null | head -n 1)"
  SERVICE_STATE="started"
  ok "OpenRC service started"
else
  warn "No supported service manager found."
  say "Binary installed at ${INSTALL_DIR}/almysama-agent"
  say "Run manually: ${INSTALL_DIR}/almysama-agent -config ${CONFIG_FILE}"
  exit 1
fi

say
say "Almysama Agent installed"
say "  Service : almysama-agent (${SERVICE_STATE:-unknown})"
[ -n "${AGENT_ID:-}" ] && say "  Agent ID: ${AGENT_ID}"
say "  Server  : ${SERVER}"
say "  Config  : ${CONFIG_FILE}"
say "  Logs    : journalctl -u almysama-agent -f"
say "  Remove  : wget -qO- https://raw.githubusercontent.com/${OWNER}/${REPO}/main/uninstall.sh | sudo sh"
