#!/usr/bin/env sh
set -eu

OWNER="zeerd2"
REPO="almysama-observatory-agent"
SERVER=""
TOKEN=""
NAME=""
VERSION="latest"
INSECURE="false"
INSTALL_DIR="/usr/local/bin"
CONFIG_DIR="/etc/almysama-agent"
CONFIG_FILE="${CONFIG_DIR}/config.json"
SERVICE_FILE="/etc/systemd/system/almysama-agent.service"

usage() {
  cat <<'EOF'
Usage:
  install.sh --server https://agent.almysama.tech --token <install-token> [--name node-name]

Options:
  --server     Agent API base URL.
  --token      One-time install token generated by Almysama Observatory.
  --name       Optional display name.
  --owner      GitHub owner, default zeerd2.
  --repo       GitHub repository, default almysama-observatory-agent.
  --version    Release version, default latest.
  --insecure   Skip TLS verification for testing.
EOF
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --server|-s) SERVER="${2:-}"; shift 2 ;;
    --token|-t) TOKEN="${2:-}"; shift 2 ;;
    --name|-n) NAME="${2:-}"; shift 2 ;;
    --owner) OWNER="${2:-}"; shift 2 ;;
    --repo) REPO="${2:-}"; shift 2 ;;
    --version) VERSION="${2:-}"; shift 2 ;;
    --insecure) INSECURE="true"; shift ;;
    --help|-h) usage; exit 0 ;;
    *) echo "Unknown option: $1" >&2; usage; exit 1 ;;
  esac
done

if [ "$(id -u)" -ne 0 ]; then
  echo "Please run as root or through sudo." >&2
  exit 1
fi

if [ -z "$SERVER" ] || [ -z "$TOKEN" ]; then
  usage >&2
  exit 1
fi

OS="$(uname -s | tr '[:upper:]' '[:lower:]')"
ARCH_RAW="$(uname -m)"
case "$ARCH_RAW" in
  x86_64|amd64) ARCH="amd64" ;;
  aarch64|arm64) ARCH="arm64" ;;
  armv7l|armv7*) ARCH="armv7" ;;
  *) echo "Unsupported architecture: $ARCH_RAW" >&2; exit 1 ;;
esac

if [ "$OS" != "linux" ]; then
  echo "Unsupported OS: $OS" >&2
  exit 1
fi

TMP_DIR="$(mktemp -d)"
cleanup() {
  rm -rf "$TMP_DIR"
}
trap cleanup EXIT INT TERM

ASSET="almysama-agent_${OS}_${ARCH}.tar.gz"
if [ "$VERSION" = "latest" ]; then
  URL="https://github.com/${OWNER}/${REPO}/releases/latest/download/${ASSET}"
else
  URL="https://github.com/${OWNER}/${REPO}/releases/download/${VERSION}/${ASSET}"
fi

echo "Downloading ${URL}"
if command -v curl >/dev/null 2>&1; then
  CURL_TLS=""
  [ "$INSECURE" = "true" ] && CURL_TLS="-k"
  curl -fsSL $CURL_TLS "$URL" -o "$TMP_DIR/agent.tar.gz"
elif command -v wget >/dev/null 2>&1; then
  WGET_TLS=""
  [ "$INSECURE" = "true" ] && WGET_TLS="--no-check-certificate"
  wget -q $WGET_TLS "$URL" -O "$TMP_DIR/agent.tar.gz"
else
  echo "curl or wget is required." >&2
  exit 1
fi

tar -xzf "$TMP_DIR/agent.tar.gz" -C "$TMP_DIR"
install -m 0755 "$TMP_DIR/almysama-agent" "${INSTALL_DIR}/almysama-agent"

mkdir -p "$CONFIG_DIR"
chmod 700 "$CONFIG_DIR"
cat > "$CONFIG_FILE" <<EOF
{
  "server": "${SERVER}",
  "install_token": "${TOKEN}",
  "name": "${NAME}",
  "report_interval_seconds": 120,
  "heartbeat_interval_seconds": 30,
  "insecure_tls": ${INSECURE}
}
EOF
chmod 600 "$CONFIG_FILE"

if command -v systemctl >/dev/null 2>&1 && [ -d /run/systemd/system ]; then
  cat > "$SERVICE_FILE" <<'EOF'
[Unit]
Description=Almysama Observatory Agent
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=/usr/local/bin/almysama-agent -config /etc/almysama-agent/config.json
Restart=always
RestartSec=5

NoNewPrivileges=true
ProtectSystem=full
ReadWritePaths=/etc/almysama-agent
PrivateTmp=true

[Install]
WantedBy=multi-user.target
EOF
  systemctl daemon-reload
  systemctl enable --now almysama-agent
  systemctl restart almysama-agent
  systemctl --no-pager --full status almysama-agent | sed -n '1,12p' || true
elif command -v rc-update >/dev/null 2>&1; then
  cat > /etc/init.d/almysama-agent <<'EOF'
#!/sbin/openrc-run
name="Almysama Observatory Agent"
command="/usr/local/bin/almysama-agent"
command_args="-config /etc/almysama-agent/config.json"
command_background=true
pidfile="/run/almysama-agent.pid"
supervisor="supervise-daemon"
respawn_delay=5
depend() {
  need net
}
EOF
  chmod +x /etc/init.d/almysama-agent
  rc-update add almysama-agent default
  rc-service almysama-agent restart
else
  echo "No supported service manager found. Binary installed at ${INSTALL_DIR}/almysama-agent" >&2
  echo "Run manually: ${INSTALL_DIR}/almysama-agent -config ${CONFIG_FILE}" >&2
  exit 1
fi

echo "Almysama Agent installed."
